import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from './tokens';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.s,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  titleContainer: {
    flex: 1,
    marginTop: 10,
  },
  title: {
    fontSize: typography.h1,
    fontWeight: 'bold',
    color: colors.primary,
  },
  subtitle: {
    fontSize: 14,
    color: colors.muted,
    marginTop: 2,
  },
  logoutButton: {
    backgroundColor: colors.accent,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  logoutButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  buttonContainer: {
    margin: 10,
  },
  outputBox: {
    margin: 10,
    padding: 15,
    backgroundColor: colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 100,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 10,
  },
  outputText: {
    fontSize: typography.body,
    color: colors.text,
    lineHeight: 20,
  },
  feedbackBox: {
    margin: 10,
    padding: 15,
    backgroundColor: '#e8f5e9',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#4caf50',
  },
  feedbackText: {
    fontSize: typography.body,
    color: '#2e7d32',
    lineHeight: 20,
  },
  loadingContainer: {
    margin: 10,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#555555',
  },
  warningText: {
    marginTop: 8,
    fontSize: 13,
    color: colors.accent,
    textAlign: 'center',
  },
  // History detail / transcript styles
  detailHeader: {
    padding: spacing.m,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  reportButton: {
    backgroundColor: '#2f80ed',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  reportButtonText: { color: colors.white, fontWeight: '700' },
  playBar: {
    height: 48,
    backgroundColor: '#f1f5f9',
    borderRadius: 24,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  messageRow: { marginTop: 12 },
  interviewerBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#f3f6f9',
    padding: 12,
    borderRadius: 12,
    maxWidth: '85%',
  },
  youBubble: {
    alignSelf: 'flex-end',
    backgroundColor: colors.white,
    padding: 12,
    borderRadius: 12,
    maxWidth: '85%',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  roleLabel: { fontSize: 12, color: colors.muted, marginTop: 8 },
  timeLabel: { fontSize: 12, color: colors.muted, marginTop: 6 },
  insightTag: {
    marginTop: 8,
    backgroundColor: '#e8f9ef',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  insightText: { color: '#1b7a44' },
  // Report / analysis styles
  scoreCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: spacing.m,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.m,
  },
  scoreNumber: { fontSize: 48, fontWeight: '800', color: '#0b2545' },
  percentText: { color: '#16a34a', marginTop: 6 },
  metricRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.m },
  metricCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: spacing.s,
    marginHorizontal: 6,
    alignItems: 'center',
  },
  smallStat: { fontSize: 18, fontWeight: '700', color: '#0b2545' },
  radarCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: spacing.s,
    alignItems: 'center',
  },
  insightSuccess: {
    marginTop: 8,
    backgroundColor: '#e6f8ef',
    borderColor: '#16a34a',
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
  },
  insightWarning: {
    marginTop: 8,
    backgroundColor: '#fff7ed',
    borderColor: '#f59e0b',
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
  },
  insightIcon: { marginRight: 8 },
});
